CREATE TABLE `messages` (
  `id` int NOT NULL AUTO_INCREMENT,
  `message_id` varchar(255) DEFAULT NULL,
  `session_id` varchar(50) DEFAULT NULL,
  `sender_phone` varchar(20) NOT NULL,
  `recipient_phone` varchar(20) DEFAULT NULL,
  `message_text` text,
  `source` enum('user','api') NOT NULL DEFAULT 'user',
  `message_type` enum('text','media','status') DEFAULT 'text',
  `original_timestamp` timestamp NULL DEFAULT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  `received_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` timestamp NULL DEFAULT NULL,
  `environment` varchar(20) DEFAULT 'production',
  `status` enum('received','processing','completed','error') DEFAULT 'received',
  `is_group` int NOT NULL,
  `direction` enum('incoming','outgoing') NOT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `message_id` (`message_id`),
  KEY `idx_sender_phone` (`sender_phone`),
  KEY `idx_received_at` (`received_at`),
  KEY `idx_status` (`status`),
  KEY `idx_received_original_ts` (`received_at`,`original_timestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=340833 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT;
CREATE TABLE `message_media` (
  `id` int NOT NULL AUTO_INCREMENT,
  `message_id` int DEFAULT NULL,
  `type` enum('audio','image','video','document') DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `file_size_formatted` varchar(20) DEFAULT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `s3_url` text,
  `s3_key` varchar(500) DEFAULT NULL,
  `local_path` varchar(500) DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `width` int DEFAULT NULL,
  `height` int DEFAULT NULL,
  `pages` int DEFAULT NULL,
  `caption` text,
  `is_voice_note` tinyint(1) DEFAULT '0',
  `transcription_status` enum('pending','success','failed','skipped') DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`),
  CONSTRAINT `message_media_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=94439 DEFAULT CHARSET=utf8mb3 COMMENT='Arquivos de mídia (áudio, imagem, vídeo, documento) das mensagens';
CREATE TABLE `message_responses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `message_id` int DEFAULT NULL,
  `ai_service` varchar(50) DEFAULT NULL,
  `raw_response` json DEFAULT NULL,
  `formatted_response` text,
  `response_type` varchar(50) DEFAULT NULL,
  `processing_time_ms` int DEFAULT NULL,
  `tokens_used` int DEFAULT NULL,
  `cost_estimate` decimal(10,6) DEFAULT NULL,
  `status` enum('success','failed','skipped') DEFAULT 'success',
  `error_message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`),
  CONSTRAINT `message_responses_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=441 DEFAULT CHARSET=utf8mb3 COMMENT='Respostas geradas pela IA (n8n, OpenAI, etc) para as mensagens';
CREATE TABLE `message_transcriptions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `media_id` int DEFAULT NULL,
  `transcription_text` text,
  `confidence` decimal(5,4) DEFAULT NULL,
  `language` varchar(10) DEFAULT 'pt-BR',
  `service_used` varchar(50) DEFAULT NULL,
  `processing_time_ms` int DEFAULT NULL,
  `status` enum('success','failed','empty') DEFAULT 'success',
  `error_message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `media_id` (`media_id`),
  CONSTRAINT `message_transcriptions_ibfk_1` FOREIGN KEY (`media_id`) REFERENCES `message_media` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Transcrições de arquivos de áudio usando OpenAI Whisper';
CREATE TABLE `phone_validations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `phone_number` varchar(20) DEFAULT NULL,
  `formatted_number` varchar(20) DEFAULT NULL,
  `validation_api_response` json DEFAULT NULL,
  `is_valid` tinyint(1) DEFAULT NULL,
  `last_validated` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_number` (`phone_number`),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_last_validated` (`last_validated`)
) ENGINE=InnoDB AUTO_INCREMENT=2003 DEFAULT CHARSET=utf8mb3 COMMENT='Cache de validações de números de telefone para otimizar performance';
CREATE TABLE `superbot_customers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `jid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `push_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_number` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_group` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `jid` (`jid`),
  KEY `idx_phone` (`phone_number`),
  KEY `idx_jid` (`jid`)
) ENGINE=InnoDB AUTO_INCREMENT=308 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `whatsapp_deliveries` (
  `id` int NOT NULL AUTO_INCREMENT,
  `message_id` int DEFAULT NULL,
  `response_id` int DEFAULT NULL,
  `delivery_type` enum('log','response','product','transcription') DEFAULT NULL,
  `recipient_phone` varchar(20) DEFAULT NULL,
  `whatsapp_message_id` varchar(255) DEFAULT NULL,
  `delivery_status` enum('sent','delivered','read','failed') DEFAULT NULL,
  `api_response` json DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `read_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `message_id` (`message_id`),
  KEY `response_id` (`response_id`),
  CONSTRAINT `whatsapp_deliveries_ibfk_1` FOREIGN KEY (`message_id`) REFERENCES `messages` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `whatsapp_deliveries_ibfk_2` FOREIGN KEY (`response_id`) REFERENCES `message_responses` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=349 DEFAULT CHARSET=utf8mb3 COMMENT='Log de todas as entregas feitas via WhatsApp API';
